repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^internal/(?:go|pprof)/
      - id: trailing-whitespace
        exclude: ^internal/(?:go|pprof)/
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        name: Insert license in comments (Go)
        args:
          - --license-filepath=scripts/LICENSE.txt
          - --comment-style=//
          - --use-current-year
          - --fuzzy-match-generates-todo
        types: [go]
        exclude: ^internal/(?:go|pprof|dwarf)/
      - id: insert-license
        name: Insert license in comments (Shell)
        args:
          - --license-filepath=scripts/LICENSE.txt
          - --comment-style=#
          - --use-current-year
          - --fuzzy-match-generates-todo
        types: [shell]
        exclude: ^internal/(?:go|pprof)/
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.1
    hooks:
      - id: golangci-lint
        entry: make go/lint-fix
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        exclude: ^internal/(?:go|pprof)/
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-2
    hooks:
      - id: shfmt
        # Google-style w/ 4-space indent
        args:
          - --write
          - --indent=4
          - --case-indent
          - --binary-next-line
        exclude: ^internal/(?:go|pprof)/
  - repo: https://github.com/google/go-jsonnet
    rev: v0.20.0
    hooks:
      - id: jsonnet-format
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
